[package]
name = "roguelike_project"
version = "0.1.0"
edition = "2021"

[dependencies]
bracket-lib = "0.8.7"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
crossbeam-utils = "0.8.7"
rand = "0.8.5"
bracket-geometry = "0.7"